name: CWTools CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    branches:    
    - master
    paths:
    - '*/**/*.txt'
    - '*/**/*.yml'
    - '*/**/*.gfx'
    - '*/**/*.gui'
    - 'localisation/**'
    - '!.*/**'
    - '!tutorial/**'
    - '!changelog.txt'
    - '!interface/credits.txt'
  pull_request:
    paths:
    - '*/**/*.txt'
    - '*/**/*.yml'
    - '*/**/*.gfx'
    - '*/**/*.gui'
    - 'localisation/**'
    - '!.*/**'
    - '!tutorial/**'
    - '!changelog.txt'
    - '!interface/credits.txt'
  
jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cwtools/cwtools-action@v1.0.0
      with:
        game: ck2
        locLanguages: "english" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload output.json
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cwtools_output
        path: output.json
