name: CWTools CI

on: [pull_request, push, workflow_dispatch] # other events may work but are not supported

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # required
    - uses: cwtools/cwtools-action@v1.0.0
      with:
        game: ck2
        modPath: "avatar - four nations restored"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, secret is automatically set by github
    - name: Upload output.json
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cwtools_output
        path: output.json
